# Generated by Django 2.0.3 on 2018-04-26 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_auto_20180425_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=80, null=True)),
                ('degree', models.CharField(blank=True, choices=[('bac', 'Бакалавриат'), ('mag', 'Магистратура')], default=None, max_length=3, null=True)),
                ('educ_start', models.SmallIntegerField(blank=True, null=True)),
                ('educ_end', models.SmallIntegerField(blank=True, null=True)),
                ('programme', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='educ_end',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='educ_start',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university',
        ),
    ]
