# Generated by Django 2.0.3 on 2018-04-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180426_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereducation',
            name='user',
        ),
    ]
